export const inputs = [
    {
      name: "nome",
      id: "nome",
      label: "Nome do Produto",
      placeholder: "Digite o nome do Produto",
      value: "",
      type: "text",
      required: true,
      classe: "input_tamanho5",
      valid : true,
      disabled : false,
    },
    {
      name: "fornecedor",
      id: "fornecedor",
      label: "Fornecedor",
      placeholder: "Selecione o Fornecedor",
      value: "",
      type: "select",
      required: true,
      classe: "input_tamanho3",
      valid : true,
      disabled : false,
    },
    
    {
      name: "marca",
      id: "marca",
      label: "Marca",
      placeholder: "Marca",
      value: "",
      type: "text",
      required: true,
      classe: "input_tamanho3",
      valid : true,
      disabled : false,    
    },{
      name: "quantidade",
      id: "quantidade",
      label: "Quantidade",
      placeholder: "Quantidade",
      value: "",
      type: "number",
      required: true,
      classe: "input_tamanho3",
      valid : true,
      disabled : false,    
    },
    {
      name: "preco",
      id: "preco",
      label: "Preço",
      placeholder: "Informe o preço",
      value: "",
      type: "data",
      required: false,
      classe: "input_tamanho3",
      valid : true,
      disabled : false,
    },
    {
      name: "dataCompra",
      id: "dataCompra",
      label: "Data de Compra",
      placeholder: "Informe a data de compra",
      value: "",
      type: "data",
      required: false,
      classe: "input_tamanho2",
      valid : true,
      disabled : false,
    },
    {
      name: "dataVencimento",
      id: "dataVencimento",
      label: "Data de Vencimento",
      placeholder: "Informe a data de vencimento",
      value: "",
      type: "date",
      required: false,
      classe: "input_tamanho2",
      valid : true,
      disabled : false,
    },
];