export const inputs = [
    {
      name: "nome",
      id: "nome",
      label: "Nome do Produto",
      placeholder: "Digite o nome do Produto",
      value: "",
      type: "text",
      required: true,
      classe: "input_tamanho2",
      valid : true,
      disabled : true,
    },
    
    {
      name: "unidadeMedida",
      id: "unidadeMedida",
      label: "Volume",
      placeholder: "Volume",
      value: "",
      type: "text",
      required: true,
      classe: "input_tamanho2",
      valid : true,
      disabled : true,
    },
    {
      name: "descricao",
      id: "descricao",
      label: "Descrição do Produto",
      placeholder: "Descrição do Produto",
      value: "",
      type: "textarea",
      required: false,
      classe: "input_tamanho1",
      valid : true,
      disabled : true,
    },];
